/* Curated Sitecore-knowledge questions, organised by topic + difficulty.
 *
 * Topics: General Sitecore · SitecoreAI · Marketplace SDK · Content SDK · Fun
 * Difficulty: easy (warm-up) · medium (practitioner) · hard (deep cut)
 *
 * The correct answer is authored first (answer: 0); the engine shuffles option
 * order at render time. Prose uses "SitecoreAI" (the current brand) but keeps
 * technical identifiers literal (xmc.*, @sitecore-marketplace-sdk/*, getPage…).
 */
import type { Question } from "./types";

export const CURATED_QUESTIONS: Question[] = [
  // ─────────────────────────────── General Sitecore ───────────────────────────
  {
    id: "g-blok",
    topic: "General Sitecore",
    difficulty: "easy",
    q: "What is Sitecore's official design system for building UI?",
    options: ["Blok", "Material", "Chakra", "Bootstrap"],
    answer: 0,
    fact: "Blok is Sitecore's design system — 65+ primitives on a shared token set.",
    source: "curated",
  },
  {
    id: "g-personalize",
    topic: "General Sitecore",
    difficulty: "easy",
    q: "Which Sitecore product powers experimentation and personalization?",
    options: ["Sitecore Personalize", "Sitecore Send", "Sitecore OrderCloud", "Sitecore Forms"],
    answer: 0,
    fact: "Sitecore Personalize (CDP) drives A/B tests and 1:1 experiences across channels.",
    source: "curated",
  },
  {
    id: "g-edge",
    topic: "General Sitecore",
    difficulty: "medium",
    q: "What is Sitecore's globally-distributed GraphQL content delivery layer called?",
    options: ["Experience Edge", "Layout Service", "Content Hub", "Horizon"],
    answer: 0,
    fact: "Experience Edge serves published content as GraphQL from a global CDN.",
    source: "curated",
  },
  {
    id: "g-contenthub",
    topic: "General Sitecore",
    difficulty: "medium",
    q: "Which Sitecore product is the DAM and content-operations hub?",
    options: ["Sitecore Content Hub", "Sitecore Discover", "Sitecore CDP", "Sitecore Connect"],
    answer: 0,
    fact: "Content Hub manages digital assets, marketing content, and product content (PCM).",
    source: "curated",
  },
  {
    id: "g-pages",
    topic: "General Sitecore",
    difficulty: "medium",
    q: "Which app is the next-gen visual page editor in Sitecore's cloud CMS?",
    options: ["Pages", "Experience Editor", "Horizon Classic", "Sitecore Forms"],
    answer: 0,
    fact: "Pages is the modern WYSIWYG editor; head apps render inside it via the editing layer.",
    source: "curated",
  },
  {
    id: "g-discover-vs-search",
    topic: "General Sitecore",
    difficulty: "hard",
    q: "Which Sitecore product is purpose-built for commerce / product discovery (vs site search)?",
    options: ["Sitecore Discover", "Sitecore Search", "Sitecore Send", "Sitecore Connect"],
    answer: 0,
    fact: "Discover targets product/commerce discovery; Search handles general site/content search.",
    source: "curated",
  },

  // ──────────────────────────────────── SitecoreAI ────────────────────────────
  {
    id: "s-whatis",
    topic: "SitecoreAI",
    difficulty: "easy",
    q: "What does SitecoreAI add on top of Sitecore's cloud-native CMS?",
    options: ["AI-native authoring & agents", "A new SQL engine", "On-prem hosting", "A jQuery plugin"],
    answer: 0,
    fact: "SitecoreAI brings AI-native authoring and agentic workflows to the cloud CMS.",
    source: "curated",
  },
  {
    id: "s-rebrand",
    topic: "SitecoreAI",
    difficulty: "easy",
    q: "SitecoreAI is the evolution of which earlier Sitecore product brand?",
    options: ["XM Cloud", "Sitecore 9", "Sitecore Commerce", "Sitecore OrderCloud"],
    answer: 0,
    fact: "XM Cloud is the older brand; technical IDs (xmc.*) stay literal even under the new name.",
    source: "curated",
  },
  {
    id: "s-agent-api",
    topic: "SitecoreAI",
    difficulty: "medium",
    q: "Which SitecoreAI REST API exposes high-level actions like create_page_with_components?",
    options: ["The Agent API", "The Layout API", "The Forms API", "The CDP API"],
    answer: 0,
    fact: "The Agent API collapses multi-step operations into single natural-language-style actions.",
    source: "curated",
  },
  {
    id: "s-auth",
    topic: "SitecoreAI",
    difficulty: "medium",
    q: "How do SitecoreAI automation clients authenticate for server-to-server API calls?",
    options: ["OAuth 2.0 client credentials", "A static API key", "Basic auth", "A session cookie"],
    answer: 0,
    fact: "Automation clients use the OAuth client-credentials grant; the JWT is sent as a Bearer token.",
    source: "curated",
  },
  {
    id: "s-host",
    topic: "SitecoreAI",
    difficulty: "hard",
    q: "Which canonical host serves SitecoreAI's authoring & publishing REST APIs?",
    options: [
      "edge-platform.sitecorecloud.io",
      "api.sitecore.net",
      "cms.sitecorecloud.io",
      "graph.sitecore.com",
    ],
    answer: 0,
    fact: "edge-platform.sitecorecloud.io is the same host for every tenant; the path prefix routes the call.",
    source: "curated",
  },
  {
    id: "s-jobs-shape",
    topic: "SitecoreAI",
    difficulty: "hard",
    q: "A SitecoreAI publishing job's POST body nests the publish mode under which path?",
    options: ["options.xmc.site.mode", "options.mode", "publish.mode", "xmc.locales.mode"],
    answer: 0,
    fact: "POST /jobs needs the nested shape options.xmc.site.{mode}; a flat body 500s on model-bind.",
    source: "curated",
  },
  {
    id: "s-createitem-id",
    topic: "SitecoreAI",
    difficulty: "hard",
    q: "SitecoreAI Authoring GraphQL createItem REJECTS which caller-supplied field?",
    options: ["id", "name", "templateId", "language"],
    answer: 0,
    fact: "createItem assigns its own id; passing one is rejected. Responses wrap under { item { … } }.",
    source: "curated",
  },

  // ─────────────────────────────────── Marketplace SDK ────────────────────────
  {
    id: "m-bridge",
    topic: "Marketplace SDK",
    difficulty: "easy",
    q: "How does a Marketplace app talk to the Cloud Portal it's embedded in?",
    options: [
      "postMessage bridge via the Marketplace SDK",
      "Direct SQL connection",
      "A shared global window object",
      "FTP polling",
    ],
    answer: 0,
    fact: "@sitecore-marketplace-sdk/client wraps a postMessage bridge between iframe and portal.",
    source: "curated",
  },
  {
    id: "m-package",
    topic: "Marketplace SDK",
    difficulty: "easy",
    q: "Which npm package is the Marketplace SDK client?",
    options: [
      "@sitecore-marketplace-sdk/client",
      "@sitecore/marketplace",
      "sitecore-portal-sdk",
      "@sitecore/app-bridge",
    ],
    answer: 0,
    fact: "@sitecore-marketplace-sdk/client; the XM Cloud data module is @sitecore-marketplace-sdk/xmc.",
    source: "curated",
  },
  {
    id: "m-context",
    topic: "Marketplace SDK",
    difficulty: "medium",
    q: "Which value must accompany almost every xmc.* call to scope it to a tenant?",
    options: ["sitecoreContextId", "tenantSecret", "apiKey", "siteCookie"],
    answer: 0,
    fact: "sitecoreContextId comes from application.context — omit it and mutations silently 200-and-do-nothing.",
    source: "curated",
  },
  {
    id: "m-fullscreen",
    topic: "Marketplace SDK",
    difficulty: "medium",
    q: "Which extension point gives a Marketplace app the full browser viewport?",
    options: ["Full screen", "Page context panel", "Custom field", "Dashboard widget"],
    answer: 0,
    fact: "Full screen (standalone) renders the app across the whole portal viewport — like this game.",
    source: "curated",
  },
  {
    id: "m-graphql-verb",
    topic: "Marketplace SDK",
    difficulty: "medium",
    q: "Which ClientSDK verb runs an xmc.authoring.graphql call?",
    options: ["client.mutate", "client.query", "client.subscribe", "client.fetch"],
    answer: 0,
    fact: "GraphQL passthroughs are POSTs, so they use client.mutate — even for read-style queries.",
    source: "curated",
  },
  {
    id: "m-unwrap",
    topic: "Marketplace SDK",
    difficulty: "hard",
    q: "In Mode A, an xmc.* query result unwraps the payload at which path?",
    options: ["result.data.data", "result.data", "result.body", "result.payload"],
    answer: 0,
    fact: "Module-key queries double-unwrap: outer .data is the SDK envelope, inner .data is the API body.",
    source: "curated",
  },
  {
    id: "m-graphql-body",
    topic: "Marketplace SDK",
    difficulty: "hard",
    q: "For xmc.authoring.graphql, where must the GraphQL body live in the options?",
    options: ["Inside params", "At the top level", "In headers", "In the query string"],
    answer: 0,
    fact: "body goes inside params alongside query; a top-level body sends an HTTP 400 with an empty payload.",
    source: "curated",
  },
  {
    id: "m-resourceaccess",
    topic: "Marketplace SDK",
    difficulty: "hard",
    q: "On a Standalone app, application.context.resourceAccess[] returns one entry per…?",
    options: ["installation across the org", "page", "logged-in user", "language"],
    answer: 0,
    fact: "Standalone is org-bound — each entry is one install (the Cloud Portal umbrella pattern).",
    source: "curated",
  },

  // ──────────────────────────────────── Content SDK ───────────────────────────
  {
    id: "c-scaffold",
    topic: "Content SDK",
    difficulty: "easy",
    q: "Which CLI scaffolds a modern Content SDK head application?",
    options: [
      "npx create-content-sdk-app@latest",
      "npx create-jss-app",
      "dotnet new sitecore-head",
      "npm init xmcloud",
    ],
    answer: 0,
    fact: "create-content-sdk-app is the canonical scaffold — Content SDK is the JSS successor.",
    source: "curated",
  },
  {
    id: "c-jss",
    topic: "Content SDK",
    difficulty: "easy",
    q: "Content SDK is the strategic successor to which older framework?",
    options: ["JSS (JavaScript Services)", "SXA", "MVC renderings", "Sitecore Habitat"],
    answer: 0,
    fact: "Content SDK supersedes JSS; JSS is now in maintenance mode heading toward EOL.",
    source: "curated",
  },
  {
    id: "c-richtext",
    topic: "Content SDK",
    difficulty: "medium",
    q: "Which Content SDK component safely renders a rich-text field?",
    options: ["<RichText>", "<InnerHtml>", "<Markup>", "<Html dangerouslySet>"],
    answer: 0,
    fact: "<RichText> handles editing chrome + sanitization for you — never inject raw HTML.",
    source: "curated",
  },
  {
    id: "c-route",
    topic: "Content SDK",
    difficulty: "medium",
    q: "In a Content SDK App Router app, the single catch-all route lives at…?",
    options: [
      "[site]/[locale]/[[...path]]/page.tsx",
      "pages/index.tsx",
      "app/router.config.ts",
      "src/main.tsx",
    ],
    answer: 0,
    fact: "One catch-all renders every Sitecore route; layout data comes from getPage().",
    source: "curated",
  },
  {
    id: "c-componentmap",
    topic: "Content SDK",
    difficulty: "medium",
    q: "Where are Content SDK components registered so layout can resolve them?",
    options: [
      ".sitecore/component-map.ts",
      "next.config.ts",
      "public/components.json",
      "app/registry.ts",
    ],
    answer: 0,
    fact: "App Router uses .sitecore/component-map.ts (Server) + component-map.client.ts (Client).",
    source: "curated",
  },
  {
    id: "c-getpage",
    topic: "Content SDK",
    difficulty: "hard",
    q: "In Content SDK App Router, which client call fetches a route's layout data?",
    options: ["getPage", "getLayoutData", "getRoute", "fetchLayout"],
    answer: 0,
    fact: "getPage(path, { site, locale }) returns layout; there's no getComponentData in App Router.",
    source: "curated",
  },
  {
    id: "c-proxy-order",
    topic: "Content SDK",
    difficulty: "hard",
    q: "What is the FIXED proxy order in a Content SDK App Router app?",
    options: [
      "Locale → Multisite → Redirects → Personalize",
      "Redirects → Locale → Personalize → Multisite",
      "Multisite → Personalize → Locale → Redirects",
      "Personalize → Redirects → Multisite → Locale",
    ],
    answer: 0,
    fact: "LocaleProxy → AppRouterMultisiteProxy → RedirectsProxy → PersonalizeProxy, in that order.",
    source: "curated",
  },
  {
    id: "c-nested-placeholder",
    topic: "Content SDK",
    difficulty: "hard",
    q: "Nested placeholders in a Content SDK head app need which component to resolve correctly?",
    options: [
      "AppPlaceholder with the injected SERVER component map",
      "A bare <Placeholder>",
      "A dynamic import()",
      "getComponentData()",
    ],
    answer: 0,
    fact: "A bare Placeholder uses the client map → 'unknown component'; AppPlaceholder + server map fixes it.",
    source: "curated",
  },

  // ──────────────────────────────────────── Fun ───────────────────────────────
  {
    id: "f-mascot",
    topic: "Fun",
    difficulty: "easy",
    q: "What's the name of the Sitecore Arcade mascot?",
    options: ["Sitecorex", "Pixel Pete", "Cubey", "Mr. Red"],
    answer: 0,
    fact: "Sitecorex — a cube with a stylized “S” face. Your quiz host today!",
    source: "curated",
  },
  {
    id: "f-tagline",
    topic: "Fun",
    difficulty: "easy",
    q: "What is the Sitecore Arcade tagline?",
    options: ["Play with your tenant.", "Ship it and grin.", "Content, but fun.", "Press start to publish."],
    answer: 0,
    fact: "“Play with your tenant.” — every Arcade game riffs on real Sitecore data or knowledge.",
    source: "curated",
  },
  {
    id: "f-face",
    topic: "Fun",
    difficulty: "easy",
    q: "Sitecorex's face is shaped like which letter?",
    options: ["S", "X", "C", "O"],
    answer: 0,
    fact: "A stylized parchment “S” — the same S as the Sitecore logo, pixel-rebuilt.",
    source: "curated",
  },
  {
    id: "f-mvp",
    topic: "Fun",
    difficulty: "medium",
    q: "In the Sitecore community, the annual “MVP” award stands for…?",
    options: ["Most Valuable Professional", "Minimum Viable Product", "Most Verified Partner", "Master of Visual Pages"],
    answer: 0,
    fact: "Most Valuable Professional — Sitecore's recognition for top community contributors.",
    source: "curated",
  },
  {
    id: "f-symposium",
    topic: "Fun",
    difficulty: "medium",
    q: "What is Sitecore's flagship annual user conference called?",
    options: ["Sitecore Symposium", "SitecoreCon", "DXP Days", "RedFest"],
    answer: 0,
    fact: "Sitecore Symposium — the big yearly gathering for the Sitecore community.",
    source: "curated",
  },
  {
    id: "f-red",
    topic: "Fun",
    difficulty: "medium",
    q: "What hex powers Sitecorex's red face (and the Arcade accent colour)?",
    options: ["#DA291C", "#E03127", "#C8102E", "#FF1A1A"],
    answer: 0,
    fact: "#DA291C — the exact red defined in the Sitecore Arcade brand kit for the mascot.",
    source: "curated",
  },
  {
    id: "f-ser-push",
    topic: "Fun",
    difficulty: "hard",
    q: "What does the Sitecore CLI command `dotnet sitecore ser push` do?",
    options: [
      "Pushes serialized items into the instance",
      "Deploys the website to Vercel",
      "Restarts IIS",
      "Publishes to Experience Edge",
    ],
    answer: 0,
    fact: "`ser push` writes serialized (YAML) items from disk into your Sitecore instance.",
    source: "curated",
  },
  {
    id: "f-chime",
    topic: "Fun",
    difficulty: "hard",
    q: "The Sitecore Arcade brand “S-chime” stinger is which three notes?",
    options: ["C5 → G5 → C6", "A4 → A4 → A4", "C4 → E4 → G4", "G5 → C5 → G5"],
    answer: 0,
    fact: "C5 → G5 → C6 square-wave — synthesized in-code via Web Audio, no .mp3 shipped.",
    source: "curated",
  },
];
