/* Curated Sitecore-knowledge questions. The correct answer is authored first
 * (answer: 0); the engine shuffles option order at render time. */
import type { Question } from "./types";

export const CURATED_QUESTIONS: Question[] = [
  {
    id: "c-xm",
    category: "Basics",
    q: "What does the “XM” in XM Cloud stand for?",
    options: ["Experience Manager", "eXtra Magic", "Xtreme Markup", "Cross Media"],
    answer: 0,
    fact: "XM = Experience Manager — Sitecore's content management core, now cloud-native.",
    source: "curated",
  },
  {
    id: "c-scaffold",
    category: "Head apps",
    q: "Which CLI scaffolds a modern Content SDK head application?",
    options: [
      "npx create-content-sdk-app@latest",
      "npx create-jss-app",
      "dotnet new sitecore-head",
      "npm init xmcloud",
    ],
    answer: 0,
    fact: "create-content-sdk-app is the canonical scaffold — Content SDK is the JSS successor.",
    source: "curated",
  },
  {
    id: "c-edge",
    category: "Delivery",
    q: "What is Sitecore's GraphQL content delivery layer called?",
    options: ["Experience Edge", "Layout Service", "Content Hub", "Horizon"],
    answer: 0,
    fact: "Experience Edge is the globally-distributed GraphQL endpoint that serves published content.",
    source: "curated",
  },
  {
    id: "c-pages",
    category: "Editing",
    q: "Which app is the visual page editor for XM Cloud?",
    options: ["Pages", "Experience Editor", "Horizon Classic", "Sitecore Forms"],
    answer: 0,
    fact: "Pages is the next-gen WYSIWYG editor; head apps render inside it via the editing layer.",
    source: "curated",
  },
  {
    id: "c-richtext",
    category: "Rendering",
    q: "In a Content SDK app, which SDK component safely renders a rich-text field?",
    options: ["<RichText>", "<InnerHtml>", "<Markup>", "<Html dangerouslySet>"],
    answer: 0,
    fact: "<RichText> from the Content SDK handles editing chrome + sanitization for you.",
    source: "curated",
  },
  {
    id: "c-multisite",
    category: "Architecture",
    q: "What pattern lets a head app resolve which site a request belongs to?",
    options: ["Multisite proxy", "Round-robin DNS", "A cookie jar", "The sitemap"],
    answer: 0,
    fact: "The multisite proxy maps hostnames to sites using .sitecore/sites.json.",
    source: "curated",
  },
  {
    id: "c-bridge",
    category: "Marketplace",
    q: "How does a Marketplace app talk to the Cloud Portal it's embedded in?",
    options: [
      "postMessage bridge via the Marketplace SDK",
      "Direct SQL connection",
      "Shared global window object",
      "FTP polling",
    ],
    answer: 0,
    fact: "@sitecore-marketplace-sdk/client wraps a postMessage bridge between iframe and portal.",
    source: "curated",
  },
  {
    id: "c-blok",
    category: "Design",
    q: "What is Sitecore's official design system for building UI?",
    options: ["Blok", "Material", "Chakra", "Bootstrap"],
    answer: 0,
    fact: "Blok is Sitecore's design system — 65+ primitives built on a shared token set.",
    source: "curated",
  },
  {
    id: "c-personalize",
    category: "Personalization",
    q: "Which Sitecore product powers experimentation and personalization?",
    options: ["Sitecore Personalize", "Sitecore Send", "Sitecore OrderCloud", "Sitecore Discover"],
    answer: 0,
    fact: "Sitecore Personalize (CDP) drives A/B tests and 1:1 experiences across channels.",
    source: "curated",
  },
  {
    id: "c-jss",
    category: "Head apps",
    q: "Content SDK is the strategic successor to which older framework?",
    options: ["JSS (JavaScript Services)", "SXA", "MVC renderings", "Sitecore Habitat"],
    answer: 0,
    fact: "Content SDK supersedes JSS; JSS is now in maintenance mode heading toward EOL.",
    source: "curated",
  },
  {
    id: "c-authoring",
    category: "Data",
    q: "Which GraphQL endpoint do you use to WRITE content in XM Cloud?",
    options: ["Authoring", "Edge / Live", "Preview", "Delivery"],
    answer: 0,
    fact: "Authoring GraphQL handles mutations; Edge/Live/Preview are read-only delivery surfaces.",
    source: "curated",
  },
  {
    id: "c-red",
    category: "Trivia",
    q: "What colour is the canonical Sitecore brand red?",
    options: ["#DA291C", "#FF0000", "#C8102E", "#E03127"],
    answer: 0,
    fact: "#DA291C — the exact red used for the Arcade mascot's face. Pixel-perfect on purpose.",
    source: "curated",
  },
  {
    id: "c-route",
    category: "Routing",
    q: "In a Next.js App Router head app, the single catch-all route lives at…",
    options: [
      "[site]/[locale]/[[...path]]/page.tsx",
      "pages/index.tsx",
      "app/router.config.ts",
      "src/main.tsx",
    ],
    answer: 0,
    fact: "One catch-all renders every Sitecore route; layout data comes from getPage().",
    source: "curated",
  },
  {
    id: "c-theme",
    category: "Theme",
    q: "Every Sitecore Marketplace app must ship which theme support?",
    options: ["Dark + light + system", "Dark only", "Light only", "High-contrast only"],
    answer: 0,
    fact: "Three-state theming is mandatory — toggle this game's theme top-right.",
    source: "curated",
  },
  {
    id: "c-mascot",
    category: "Fun",
    q: "What's the name of the Sitecore Arcade mascot?",
    options: ["Sitecorex", "Pixel Pete", "Cubey", "Mr. Red"],
    answer: 0,
    fact: "Sitecorex — a cube with a stylized “S” face. Your quiz host today!",
    source: "curated",
  },
  {
    id: "c-context",
    category: "Marketplace SDK",
    q: "Which value must accompany almost every xmc.* call to scope it to a tenant?",
    options: ["sitecoreContextId", "tenantSecret", "apiKey", "siteCookie"],
    answer: 0,
    fact: "sitecoreContextId (from application.context) scopes XMC calls — this very game uses it.",
    source: "curated",
  },
];
